#pragma once
#include <lvgl.h>

// These symbols are generated by tools/generate_poppins_lvgl.ps1 from user's local poppins.zip.
// The actual font data is not stored in this patch. Run generate_poppins_lvgl.bat first.
LV_FONT_DECLARE(lv_font_poppins_13)
LV_FONT_DECLARE(lv_font_poppins_16)
LV_FONT_DECLARE(lv_font_poppins_20)
LV_FONT_DECLARE(lv_font_poppins_24)
LV_FONT_DECLARE(lv_font_poppins_34)
LV_FONT_DECLARE(lv_font_poppins_36)
LV_FONT_DECLARE(lv_font_poppins_40)
